### ISSUE TITLE
source/EmptyCharacter.hx:31: characters 9-15 : Normal variables cannot be accessed with 'super', use 'this' instead

### ISSUE THREAD

**Issue by KGAMERDEV** [superpowers04/Super-Engine#7]
source/EmptyCharacter.hx:31: characters 9-15 : Normal variables cannot be accessed with 'super', use 'this' instead
pls help

**Comment by superpowers04** [comment]
Replace "super" with "this" in EmptyCharacter.hx. at line 31. The next update will have this fixed
